Added remove_lab and remove_token commands
kernelci/kci_admin pull request #10
Opened 2019-04-17 11:05 UTC by mgalka

Added commands to remove tokens and labs from kernelci-backend.
The commands utilise /lab and /token delete handlers from the backend. 

remove_token command doesn't provide any extra checks apart from what's been implemented in the backend, therefore it's possible to e.g. remove a lab token without any notice.

2019-04-17 17:30 UTC, khilman approved these changes
Very nice, we've been missing these features.

2019-04-18 06:52 UTC, gctucker requested changes
Commit messages should be in the present tense i.e. "add remove_token command" rather than "added".  Also the command is "remove_lab" but the commit message says "lab_remove".

I think the README.md needs to be updated slightly with these new commands.

Other than those cosmetic things, I've tested it OK with the backend fix applied from https://github.com/kernelci/kernelci-backend/pull/125, thanks!

2019-04-18 06:52 UTC, gctucker commented on kci_admin/lab.py
> +    return kci_request_delete(hostname, "/lab/{}".format(id_))
Nitpick: missing trailing newline

2019-04-18 14:17 UTC, mgalka commented on kci_admin/lab.py
> +    return kci_request_delete(hostname, "/lab/{}".format(id_))
Commit messages corrected
Trailing newline added
README.md updated

2019-04-18 15:46 UTC, gctucker approved these changes

2019-04-18 15:50 UTC, gctucker commented
Thanks, this can now be merged.

See also the comments I put on https://github.com/kernelci/kernelci-backend/pull/125, which needs to be merged for the `delete_lab` command to work.

2019-04-18 15:50 UTC, merged